---
ttitle: "澳門第三次全民核酸檢測站地圖"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggmap)
library(grid)
library(gridExtra)
library(dplyr)
library(reshape)
library(ggplot2)
library(stringr)
library(plotly)
register_google(key = "AIzaSyD9z90fvzxmOhRzoNbxbwOmuIXI6CVKcTE")
ggmap_hide_api_key()
```

## 數據來源  

來源為核酸檢測站，取用採樣點數目參考  
[https://eservice.ssm.gov.mo/aptmon/aptmon/ch]  


## 核酸採樣點的數據準備  

數據更新於以下時間

```{r scraped-preparation, message=FALSE, echo=FALSE}
paths <- dir('../aptmon-scraping/', full.names=TRUE)
locationfilename <- tail(paths, 1)
filetimestr <- sub(".csv", "",sub(".*-", "", locationfilename))
filetime <- strptime(filetimestr,"%Y%m%d%H%M%S")
filectime <- tail(file.info(paths)$ctime, 1)
filectime
```

```{r transform-load-dataset, message=FALSE, echo=FALSE}
scrp <- read.csv(locationfilename, na = "---")
scrp$MapLoc <- ifelse(scrp$Location == "科大體育館","Macao, 澳門科技大學室內體育館 Gymnasium",scrp$Location)
scrp[grep(".*工人體育場", scrp$Location, perl=T), ]$MapLoc <- "Macao, 工人體育場館"
scrp[grep(".*1樓", scrp$Location, perl=T), ]$MapLoc <- "望廈體育中心 Centro Desportivo Mong-Há"
scrp$DateTime <- as.POSIXct(filetime)
scrp$WaitingQueue <- as.numeric(as.character(sub("*人", "", scrp$輪候人數)))
scrp$WaitingMinutes <- as.numeric(as.character(sub("分鐘", "",sub(".*>", "", scrp$等候時間))))
LonLat <- mutate_geocode(scrp, MapLoc)
LonLat$area <- ifelse(LonLat$lat>=22.17,'macao','cotai,macao')
```

## 地圖  

右側 A/B/C 氣泡為類別，點擊可篩選。氣泡越大表示排隊需時越短。

```{r plot-location, message=FALSE}
plot <- ggmap(get_map(location = "taipa, macao", zoom = 12), darken = .5, 
base_layer = ggplot(data = LonLat, aes(x = lon, y = lat, label=paste(Location,WaitingQueue,"人")))) +
geom_point(aes(colour = 類別, size = WaitingMinutes, alpha = .2), data = LonLat) +
geom_text(colour = 'white', size = 4, check_overlap = T) +
scale_size(range = c(0, 12), trans="reverse") +
scale_color_viridis_d(option = "magma")

ggplotly(plot)
```